### ISSUE TITLE
Nick could you clarify your comment on Sampling dist 

### ISSUE THREAD

**Issue by bonnfire** [ProjectMOSAIC/oiLabs-mosaic2#30]
I write "Note that since we are sampling with replacement, we 
use the `resample()` function instead of `sample_n()`.", to which you 
comment "Why?" 
Could you expand your thoughts here? 
@nicholasjhorton

**Comment by nicholasjhorton** [comment]
I think that this is sufficiently clear here.  Next up is the cleanup of the looping example immediately after that section (and the introduction of do()).  Can you please share of your commit of that draft when you have put it together?

**Comment by rpruim** [comment]
Should we use `sample()` or `sample_n()`?

**Comment by nicholasjhorton** [comment]
We inherited dplyr::sample_n() from the earlier version, since it samples rows.  Are you suggesting base::sample() or mosaic::sample()?
