### ISSUE TITLE
migrate intro to data

### ISSUE THREAD

**Issue by bonnfire** [ProjectMOSAIC/oiLabs-mosaic2#5]
Doesn't seem like ggformula takes in tables as the formula argument, so we have to omit the message that tables can be nested within the plotting function. If someone knows a way around this, please let me know!

**Comment by nicholasjhorton** [comment]
There will definitely be places where you need to change the accompanying text.  This sounds like one.  Please post a link to a commit and I'd be glad to review.

**Comment by bonnfire** [comment]
Thank you for clarifying! You can find the first iteration of the edited version here 3b75f4fdc94eabcf4ba53280f47497f51c43d3d1
Note for self* vcd::mosaic for the mosaic translations
