### ISSUE TITLE
migration of normal distribution

### ISSUE THREAD

**Issue by bonnfire** [ProjectMOSAIC/oiLabs-mosaic2#7]
@nicholasjhorton do you mind taking a look at the ggformula work? the default bins are different than those written into base, and I'm not sure if you would like to add bin arguments to better match the original graphics? Also, what are your thoughts on proportion histogram? I couldn't find documentation for it.
89bf26298b9a455c414b6b9348810f82f393968f

**Comment by rpruim** [comment]
density histograms are made with `gf_dhistogram()`.
