### ISSUE TITLE
migration to ggformula

### ISSUE THREAD

**Issue by bonnfire** [ProjectMOSAIC/oiLabs-mosaic2#8]
Intro to R and RStudio: 5e0ee2eb0251524ed159dbcc6ff0c4a13d35562b
Introduction to Data: e9ba30cbcf10012c749ab7cf09607df565f66274
Probability: 1dc2086fc0c39c4d3271617fc8976e63f80a3554
Distributions: 3e83cc24fffd9d080fd66cbe8d5bbe7355e397df
Intro to Inference: 3e83cc24fffd9d080fd66cbe8d5bbe7355e397df
Confidence Levels: 75678d9f03c4e11857b3a23b05a6a806451352d4
Inf. for Numerical Data: 1b512133e2404be6e60361dfad879bcaa906d14b
Inf. for Categorical Data: fc45fae6dc85592d0a4b585eed5b332a607cb308
Linear Regression: 16ba2a0e3c7daaf5b4a6dc7e5f68c5a1faaadf07
Multiple Regression: 13292ac22f2fa8841f3f7df7f146e8a66e46335f

*Not on website, but the folder/files existed in the repo 
The Normal Distribution: 272fd6e21dcefd2f3973cee75665e06647eaeb9d

Iteration: I

**Comment by nicholasjhorton** [comment]
I'm ready to review these changes.

**Comment by nicholasjhorton** [comment]
@bonnfire the transition to ggformula is shaping up beautifully.  I will give you specific comments on hardcopies I brought with me on the plane but have the following suggestions for now:

(1) there are some stray "histogram()" calls

(2) do you want to add () after reference to R functions (e.g. `mean` would become `mean()`?  I suspect that this looks better.

(3) Can you please ensure that "library(mosaic)" is included with the other library calls?

It should be straightforward to address my other comments when I see you on Tuesday.  Kudos for your work on this front!
